language: php

php:
 - 7.2

before_script:
 - echo | pecl install channel://pecl.php.net/yaml-2.0.2
 
before_install:
  - chmod +x tests/travis.sh

script:
 - ./tests/travis.sh

notifications:
 email: false
 webhooks: https://discordapp.com/api/webhooks/468015163677736969/Qb5r1VMO2cPLb_LnhpUeej4pZf_hT_GElzSTn6IMjqLbo-izSvVqXizWXnUqOmsfbNiL
