name: HyperdrivePE
main: ZtechNetwork\HyperdrivePE
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10, 4.0.0-ALPHA1]
version: 1.0.0
author: ZtechNetwork[LeronDoesGM]

commands:
    hyper:
        usage: /hyper <quit/create>
        description: Main Command for creating hyperdrive games and leaving the game.