name: HyperdrivePE
main: ZtechNetwork\HyperdrivePE
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9]
version: 1.0.0
author: ZtechNetwork[LeronDoesGM]

commands:
    hyper:
        usage: /hyper
        description: Main Command for creating hyperdrive games and leaving the game.